services:
  frontend:
    build:
      context: .
      args:
        VITE_API_USER_URL: http://localhost:8000
        VITE_API_RECIPE_URL: http://localhost:8001
        VITE_API_SEARCH_URL: http://localhost:8003
        VITE_API_SOCIAL_URL: http://localhost:8002
        VITE_API_SHOPPING_URL: http://localhost:8004
        VITE_USE_MOCK_API: "false"
    ports: ["5173:80"]
    networks:
      - personalcook_net

networks:
  personalcook_net:
    external: true
    name: personalcook-net
